const center_x = 117.3;
const center_y = 172.8;
const scale_x = 0.02072;
const scale_y = 0.0205;

CUSTOM_CRS = L.extend({}, L.CRS.Simple, {
    projection: L.Projection.LonLat,
    scale: function(zoom) {

        return Math.pow(2, zoom);
    },
    zoom: function(sc) {

        return Math.log(sc) / 0.6931471805599453;
    },
	distance: function(pos1, pos2) {
        var x_difference = pos2.lng - pos1.lng;
        var y_difference = pos2.lat - pos1.lat;
        return Math.sqrt(x_difference * x_difference + y_difference * y_difference);
    },
	transformation: new L.Transformation(scale_x, center_x, -scale_y, center_y),
    infinite: true
});

var SateliteStyle = L.tileLayer('mapStyles/styleSatelite/{z}/{x}/{y}.jpg', {minZoom: 0,maxZoom: 8,noWrap: true,continuousWorld: false,attribution: 'Online map GTA V',id: 'SateliteStyle map',}),
	AtlasStyle	= L.tileLayer('mapStyles/styleAtlas/{z}/{x}/{y}.jpg', {minZoom: 0,maxZoom: 5,noWrap: true,continuousWorld: false,attribution: 'Online map GTA V',id: 'styleAtlas map',});
	// GridStyle	= L.tileLayer('mapStyles/styleGrid/{z}/{x}/{y}.png', {minZoom: 0,maxZoom: 5,noWrap: true,continuousWorld: false,attribution: 'Online map GTA V',id: 'styleGrid map',});

var PosGroup = L.layerGroup();
var Vinewood = L.layerGroup();
var SudLS = L.layerGroup();
var SudOuestLS = L.layerGroup();
var CentreVille = L.layerGroup();
var QuartierLS = L.layerGroup();
var MarinaPlage = L.layerGroup();
var MirrorPark = L.layerGroup();
var DelPerroVespucci = L.layerGroup();
var Univ = L.layerGroup();
var Nord = L.layerGroup();



var Icons = {
	"All 10-20" :PosGroup,
    "Vinewood" :Vinewood,
    "Sud LS" :SudLS,
    "Sud Ouest LS" :SudOuestLS,
    "Centre Ville" : CentreVille,
    "Quartier LS" :QuartierLS,
    "Marina / Plage" :MarinaPlage,
    "Mirror Park" :MirrorPark,
    "Bellevue / Del Perro / Vespucci" :DelPerroVespucci,
    "Université" : Univ,
    "Nord" : Nord,

};

var mymap = L.map('map', {
    crs: CUSTOM_CRS,
    minZoom: 1,
    maxZoom: 5,
    Zoom: 5,
    maxNativeZoom: 5,
    preferCanvas: true,
    layers: [SateliteStyle],
    center: [0, 0],
    zoom: 3,
});

var layersControl = L.control.layers({ "Satelite": SateliteStyle,"Atlas": AtlasStyle}, Icons).addTo(mymap);
// var layersControl = L.control.layers({ "Satelite": SateliteStyle,"Atlas": AtlasStyle,"Grid":GridStyle}, Icons).addTo(mymap);


function customIcon(icon){
	return L.icon({
		iconUrl: `blips/${icon}.png`,
		iconSize:     [20, 20],
		iconAnchor:   [20, 20], 
		popupAnchor:  [-10, -27]
	});
}

var X  = 0;
var Y = 0;

//L.marker([haut bas,gauche droite], {icon: customIcon(1)}).addTo(Icons["All 10-20"]).bindPopup("Description");
//'<div style="text-align:center;"><h3>Lieu</h3><a href="../img/nom-img.png" target="_blank"><img src="../img/nom-img.png" alt="Lieu" style="width:300px;height:auto;border-radius:8px;"></a></div>'

//Secteur Vinewood
L.marker([1575,-415], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Boule Orange</h3><a href="https://files.catbox.moe/jg94i5.jpg" target="_blank"><img src="https://files.catbox.moe/jg94i5.jpg" alt="Boule Orange" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1125,-400], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Observatoire</h3><a href="https://files.catbox.moe/83h2ix.jpg" target="_blank"><img src="https://files.catbox.moe/83h2ix.jpg" alt="Observatoire" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([860,-800], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Parc à chiens</h3><a href="https://files.catbox.moe/mepbxu.jpg" target="_blank"><img src="https://files.catbox.moe/mepbxu.jpg" alt="Parc à chiens" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([880,-80], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Villas Lac / La Goutte</h3><a href="https://files.catbox.moe/ipx0g8.jpg" target="_blank"><img src="https://files.catbox.moe/ipx0g8.jpg" alt="Villas Lac" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1175,230], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Sisyphus</h3><a href="https://files.catbox.moe/cre01h.jpg" target="_blank"><img src="https://files.catbox.moe/cre01h.jpg" alt="Sisyphus" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://files.catbox.moe/9nhck6.jpg" target="_blank"><img src="https://files.catbox.moe/9nhck6.jpg" alt="Sisyphus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1200,675], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Lettres Vinewood</h3><a href="https://files.catbox.moe/iqc33q.jpg" target="_blank"><img src="https://files.catbox.moe/iqc33q.jpg" alt="Lettres Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1100,1400], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Fuente Blanca</h3><a href="https://files.catbox.moe/w17zsg.jpg" target="_blank"><img src="https://files.catbox.moe/w17zsg.jpg" alt="Fuente Blanca" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([800,1550], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Pipeline</h3><a href="https://i.imgur.com/YGGmroX.jpeg" target="_blank"><img src="https://i.imgur.com/YGGmroX.jpeg" alt="Pipeline" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([600,700], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Vinewood Bowl</h3><a href="../img/vinewood-bowl.png" target="_blank"><img src="../img/vinewood-bowl.png" alt="Vinewood Bowl" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/vinewood-bowl-zone.png" target="_blank"><img src="../img/vinewood-bowl-zone.png" alt="Vinewood Bowl" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([320,-755], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Eclipse Tower</h3><a href="../img/eclipse-tower.png" target="_blank"><img src="../img/eclipse-tower.png" alt="Eclipse Tower" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([340,-35], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Manoir Blanc</h3><a href="../img/manoir-blanc.png" target="_blank"><img src="../img/manoir-blanc.png" alt="Manoir Blanc" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([200,75], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Alien</h3><a href="../img/alien.png" target="_blank"><img src="../img/alien.png" alt="Alien" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([330,360], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>LTD Vinewood</h3><a href="../img/ltd-vinewood.png" target="_blank"><img src="../img/ltd-vinewood.png" alt="LTD Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([260,650], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Station Essence VW</h3><a href="../img/station-essence-vw.png" target="_blank"><img src="../img/station-essence-vw.png" alt="Station Essence VW" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([170,355], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Cinema</h3><a href="../img/cinema.png" target="_blank"><img src="../img/cinema.png" alt="Cinema" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-20,600], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>PDP Vinewood</h3><a href="../img/pdp-vinewood.png" target="_blank"><img src="../img/pdp-vinewood.png" alt="PDP Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([80,320], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Parking Jaune</h3><a href="../img/parking-jaune.png" target="_blank"><img src="../img/parking-jaune.png" alt="Parking Jaune" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-355,405], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Mexico</h3><a href="../img/mexico.png" target="_blank"><img src="../img/mexico.png" alt="Mexico" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-300,330], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Fleeca Mexico</h3><a href="../img/fleeca-mexico.png" target="_blank"><img src="../img/fleeca-mexico.png" alt="Fleeca Mexico" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([290,160], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Marylin Monroe</h3><a href="../img/marylin-monroe.png" target="_blank"><img src="../img/marylin-monroe.png" alt="Marylin Monroe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-400,100], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Chantier Alta Street</h3><a href="../img/chantier-alta-street.png" target="_blank"><img src="../img/chantier-alta-street.png" alt="Chantier Alta Street" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-250,-175], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Rockford Plaza</h3><a href="../img/rockford-plaza-gauche.png" target="_blank"><img src="../img/rockford-plaza-gauche.png" alt="Rockford Plaza" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/rockford-plaza-droite.png" target="_blank"><img src="../img/rockford-plaza-droite.png" alt="Rockford Plaza" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-200,-525], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Ancien Gouv</h3><a href="../img/ancien-gouv.png" target="_blank"><img src="../img/ancien-gouv.png" alt="Ancien Gouv" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-140,-350], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>LS Custom</h3><a href="../img/ls-custom.png" target="_blank"><img src="../img/ls-custom.png" alt="LS Custom" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([60,-670], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Epsilon</h3><a href="../img/epsilon.png" target="_blank"><img src="../img/epsilon.png" alt="Epsilon" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([280,-550], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Tequilala</h3><a href="../img/tequilala.png" target="_blank"><img src="../img/tequilala.png" alt="Tequilala" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([65,-55], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Benefactor</h3><a href="../img/benefactor.png" target="_blank"><img src="../img/benefactor.png" alt="Benefactor" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-20,-750], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Église Rockford</h3><a href="../img/eglise-rockford.png" target="_blank"><img src="../img/eglise-rockford.png" alt="Église Rockford" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([215,270], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Pacific Bank</h3><a href="../img/pacific-bank.png" target="_blank"><img src="../img/pacific-bank.png" alt="Pacific Bank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([90,80], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Go Postal</h3><a href="../img/go-postal.png" target="_blank"><img src="../img/go-postal.png" alt="Go Postal" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Sud Los Santos
L.marker([-2100,950], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Wardog</h3><a href="../img/wardog.png" target="_blank"><img src="../img/wardog.png" alt="Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2350,-385], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Vert</h3><a href="../img/pont-vert.png" target="_blank"><img src="../img/pont-vert.png" alt="Pont Vert" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2650,800], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Rouge</h3><a href="../img/pont-rouge.png" target="_blank"><img src="../img/pont-rouge.png" alt="Pont Rouge" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2340,370], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Rancho / Pont Vagos</h3><a href="../img/pont-vagos.png" target="_blank"><img src="../img/pont-vagos.png" alt="Pont Rancho / Pont Vagos" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2600,-150], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Chantier Naval</h3><a href="../img/chantier-naval-nord.png" target="_blank"><img src="../img/chantier-naval-nord.png" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/chantier-naval-sud.png" target="_blank"><img src="../img/chantier-naval-sud.png" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/chantier-naval-zone.png" target="_blank"><img src="../img/chantier-naval-zone.png" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3000,225], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Bugstars</h3><a href="../img/bugstars.png" target="_blank"><img src="../img/bugstars.png" alt="Bugstars" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/bugstars-zone.png" target="_blank"><img src="../img/bugstars-zone.png" alt="Bugstars" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3100,550], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>MerryWeather</h3><a href="../img/merryweather.png" target="_blank"><img src="../img/merryweather.png" alt="MerryWeather" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/merryweather-zone.png" target="_blank"><img src="../img/merryweather-zone.png" alt="MerryWeather" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2850,-450], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Post OP</h3><a href="../img/post-op.png" target="_blank"><img src="../img/post-op.png" alt="Post OP" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/post-op-zone.png" target="_blank"><img src="../img/post-op-zone.png" alt="Post OP" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1950,1600], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pétrole</h3><a href="../img/petrole-nord.png" target="_blank"><img src="../img/petrole-nord.png" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/petrole-sud.png" target="_blank"><img src="../img/petrole-sud.png" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/petrole-zone.png" target="_blank"><img src="../img/petrole-zone.png" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2525,900], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Cypress</h3><a href="../img/cypress.png" target="_blank"><img src="../img/cypress.png" alt="Cypress" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2150,825], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Ammunation Wardog</h3><a href="../img/ammunation-wardog.png" target="_blank"><img src="../img/ammunation-wardog.png" alt="Ammunation Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2000,1070], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Fonderie</h3><a href="../img/fonderie.png" target="_blank"><img src="../img/fonderie.png" alt="Fonderie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2130,975], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Abattoir / Boucherie / Raven</h3><a href="../img/abattoir-nord.png" target="_blank"><img src="../img/abattoir-nord.png" alt="Abattoir / Boucherie / Raven" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/abattoir-sud.png" target="_blank"><img src="../img/abattoir-sud.png" alt="Abattoir / Boucherie / Raven" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2475,1070], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Casse Bus</h3><a href="../img/casse-bus.png" target="_blank"><img src="../img/casse-bus.png" alt="Casse Bus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3310,1222], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Amazon</h3><a href="../img/amazon.png" target="_blank"><img src="../img/amazon.png" alt="Amazon" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Sud Ouest LS
L.marker([-2025,-1100], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>LS Custom Sud / LS Custom Aeroport</h3><a href="../img/lscustom-sud.png" target="_blank"><img src="../img/lscustom-sud.png" alt="LS Custom Sud / LS Custom Aeroport" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1750,-525], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Casse</h3><a href="../img/casse.png" target="_blank"><img src="../img/casse.png" alt="Casse" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2000,-250], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Maze Bank Arena</h3><a href="../img/maze-bank-arena.png" target="_blank"><img src="../img/maze-bank-arena.png" alt="Maze Bank Arena" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2700,-975], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Aéroport</h3><a href="../img/aeroport.png" target="_blank"><img src="../img/aeroport.png" alt="Aéroport" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/aeroport-zone.png" target="_blank"><img src="../img/aeroport-zone.png" alt="Aéroport" style="width:300px;height:auto;border-radius:8px;"></a></div>');


//Secteur Centre Ville
L.marker([-600,345], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Pillbox Haut</h3><a href="../img/pillbox-haut.png" target="_blank"><img src="../img/pillbox-haut.png" alt="Pillbox Haut" style="width:300px;height:auto;border-radius:8px;"></a><h3>Pillbox Bas</h3><a href="../img/pillbox-bas.png" target="_blank"><img src="../img/pillbox-bas.png" alt="Pillbox Bas" style="width:300px;height:auto;border-radius:8px;"></a><h3>Tunnel Pillbox</h3><a href="../img/tunnel-pillbox.png" target="_blank"><img src="../img/tunnel-pillbox.png" alt="Tunnel Pillbox" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-750,155], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>FIB</h3><a href="../img/fib-tour.png" target="_blank"><img src="../img/fib-tour.png" alt="FIB" style="width:300px;height:auto;border-radius:8px;"></a><h3>Parking FIB</h3><a href="../img/fib-parking-est.png" target="_blank"><img src="../img/fib-parking-est.png" alt="Parking FIB" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/fib-parking-ouest.png" target="_blank"><img src="../img/fib-parking-ouest.png" alt="Parking FIB" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-700,-10], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Gruppe6 / Union Depository</h3><a href="../img/gruppe6-avant.png" target="_blank"><img src="../img/gruppe6-avant.png" alt="Gruppe6 / Union Depository" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/gruppe6-arriere.png" target="_blank"><img src="../img/gruppe6-arriere.png" alt="Gruppe6 / Union Depository" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-620,-140], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Arcadius</h3><a href="../img/arcadius.png" target="_blank"><img src="../img/arcadius.png" alt="Arcadius" style="width:300px;height:auto;border-radius:8px;"></a><h3>Parking Arcadius</h3><a href="../img/arcadius-ouest.png" target="_blank"><img src="../img/arcadius-ouest.png" alt="Parking Arcadius" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/arcadius-est.png" target="_blank"><img src="../img/arcadius-est.png" alt="Parking Arcadius" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-640,-265], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Globe</h3><a href="../img/globe.png" target="_blank"><img src="../img/globe.png" alt="Globe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-780,-300], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Rouge</h3><a href="../img/parking-rouge-sud.png" target="_blank"><img src="../img/parking-rouge-sud.png" alt="Parking Rouge" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/parking-rouge-nord.png" target="_blank"><img src="../img/parking-rouge-nord.png" alt="Parking Rouge" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-780,-440], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Blanc</h3><a href="../img/parking-blanc.png" target="_blank"><img src="../img/parking-blanc.png" alt="Parking Blanc" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-620,-520], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Musée</h3><a href="../img/musee.png" target="_blank"><img src="../img/musee.png" alt="Musée" style="width:300px;height:auto;border-radius:8px;"></a><h3>Tunnel Musée</h3><a href="../img/musee-tunnel.png" target="_blank"><img src="../img/musee-tunnel.png" alt="Tunnel Musée" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-765,-670], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Rose</h3><a href="../img/parking-rose.png" target="_blank"><img src="../img/parking-rose.png" alt="Parking Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-725,-760], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Cathédrale</h3><a href="../img/cathedrale.png" target="_blank"><img src="../img/cathedrale.png" alt="Cathédrale" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-950,-700], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>LTD Little Seoul</h3><a href="../img/ltd-little-seoul.png" target="_blank"><img src="../img/ltd-little-seoul.png" alt="LTD Little Seoul" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,-555], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Weazel News / Weazel</h3><a href="../img/weazel.png" target="_blank"><img src="../img/weazel.png" alt="Weazel News / Weazel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-980,-460], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chantier Weazel</h3><a href="../img/chantier-weazel.png" target="_blank"><img src="../img/chantier-weazel.png" alt="Chantier Weazel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,-310], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Pole Emploi</h3><a href="../img/parking-pole-emploi.png" target="_blank"><img src="../img/parking-pole-emploi.png" alt="Parking Pole Emploi" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-840,-60], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Tour Maze Bank</h3><a href="../img/maze-bank-tower.png" target="_blank"><img src="../img/maze-bank-tower.png" alt="Tour Maze Bank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1120,-30], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Ancien Concess</h3><a href="../img/ancien-concess.png" target="_blank"><img src="../img/ancien-concess.png" alt="Ancien Concess" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1040,-120], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chantier Concess</h3><a href="../img/chantier-concess.png" target="_blank"><img src="../img/chantier-concess.png" alt="Chantier Concess" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1090,150], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Caesar</h3><a href="../img/parking-caesar.png" target="_blank"><img src="../img/parking-caesar.png" alt="Caesar" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-880,60], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Ancien Parking MCD</h3><a href="../img/ancien-parking-mcd.png" target="_blank"><img src="../img/ancien-parking-mcd.png" alt="Ancien Parking MCD" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,215], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Places des cubes</h3><a href="../img/place-des-cubes.png" target="_blank"><img src="../img/place-des-cubes.png" alt="Places des cubes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1110,470], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Briques</h3><a href="../img/parking-briques.png" target="_blank"><img src="../img/parking-briques.png" alt="Parking Briques" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1010,470], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>PDP Mission Row</h3><a href="../img/mission-row.png" target="_blank"><img src="../img/mission-row.png" alt="PDP Mission Row" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-770,472], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chinatown</h3><a href="../img/chinatown.png" target="_blank"><img src="../img/chinatown.png" alt="Chinatown" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-640,450], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Entrepôt de Bus</h3><a href="../img/entrepot-bus.png" target="_blank"><img src="../img/entrepot-bus.png" alt="Entrepôt de Bus" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Quartier LS
L.marker([-1345,-200], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Bennys</h3><a href="../img/bennys.png" target="_blank"><img src="../img/bennys.png" alt="Bennys" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1560,-85], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Forum Drive / Chamberlain</h3><a href="../img/forum-drive.png" target="_blank"><img src="../img/forum-drive.png" alt="Forum Drive / Chamberlain" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/forum-drive-zone.png" target="_blank"><img src="../img/forum-drive-zone.png" alt="Forum Drive / Chamberlain" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1960,120], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Groove Street / Raquette</h3><a href="../img/groove-street.png" target="_blank"><img src="../img/groove-street.png" alt="Groove Street / Raquette" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1770,60], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Mega Mall</h3><a href="../img/mega-mall.png" target="_blank"><img src="../img/mega-mall.png" alt="Mega Mall" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1575,190], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Météorite</h3><a href="../img/meteorite.png" target="_blank"><img src="../img/meteorite.png" alt="Météorite" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1620,260], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Librairie</h3><a href="../img/librairie.png" target="_blank"><img src="../img/librairie.png" alt="Librairie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1700,380], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Parking Davis</h3><a href="../img/parking-davis.png" target="_blank"><img src="../img/parking-davis.png" alt="Parking Davis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1845,480], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Rancho Nord</h3><a href="../img/rancho-nord-haut.png" target="_blank"><img src="../img/rancho-nord-haut.png" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/rancho-nord-sud.png" target="_blank"><img src="../img/rancho-nord-sud.png" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/rancho-nord-zone.png" target="_blank"><img src="../img/rancho-nord-zone.png" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2030,310], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Rancho Sud</h3><a href="../img/rancho-sud.png" target="_blank"><img src="../img/rancho-sud.png" alt="Rancho Sud" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1730,150], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Coiffeur Davis</h3><a href="../img/coiffeur-davis.png" target="_blank"><img src="../img/coiffeur-davis.png" alt="Coiffeur Davis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1325,160], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Unicorn</h3><a href="../img/unicorn.png" target="_blank"><img src="../img/unicorn.png" alt="Unicorn" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1395,260], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Morgue</h3><a href="../img/morgue.png" target="_blank"><img src="../img/morgue.png" alt="Morgue" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1450,350], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Medical Center</h3><a href="../img/medical-center.png" target="_blank"><img src="../img/medical-center.png" alt="Medical Center" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1350,810], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>La Mesa</h3><a href="../img/la-mesa-sud.png" target="_blank"><img src="../img/la-mesa-sud.png" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/la-mesa-nord.png" target="_blank"><img src="../img/la-mesa-nord.png" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/la-mesa-zone.png" target="_blank"><img src="../img/la-mesa-zone.png" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1550,1170], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Saint Fiacre</h3><a href="../img/saint-fiacre.png" target="_blank"><img src="../img/saint-fiacre.png" alt="Saint Fiacre" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1630,1345], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>El Burro</h3><a href="../img/el-burro-zone.png" target="_blank"><img src="../img/el-burro-zone.png" alt="El Burro" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1645,960], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Fridgit</h3><a href="../img/fridgit-dessus.png" target="_blank"><img src="../img/fridgit-dessus.png" alt="Fridgit" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/fridgit-passage.png" target="_blank"><img src="../img/fridgit-passage.png" alt="Fridgit" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1780,750], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>SSX</h3><a href="../img/ssx.png" target="_blank"><img src="../img/ssx.png" alt="SSX" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1630,700], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Y</h3><a href="../img/y.png" target="_blank"><img src="../img/y.png" alt="Y" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1540,465], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Quartier Ukrainien</h3><a href="../img/quartier-ukrainien.png" target="_blank"><img src="../img/quartier-ukrainien.png" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/quartier-ukrainien-bat.png" target="_blank"><img src="../img/quartier-ukrainien-bat.png" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/quartier-ukrainien-zone.png" target="_blank"><img src="../img/quartier-ukrainien-zone.png" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Marina/Plage
L.marker([-1300,-1300], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Magasin Masque</h3><a href="../img/magasin-masque.png" target="_blank"><img src="../img/magasin-masque.png" alt="Magasin Masque" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1650,-1150], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Tennis Plage</h3><a href="../img/tennis-plage.png" target="_blank"><img src="../img/tennis-plage.png" alt="Tennis Plage" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1310,-1000], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Requin</h3><a href="../img/requin.png" target="_blank"><img src="../img/requin.png" alt="Requin" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1325,-775], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Marina</h3><a href="../img/marina.png" target="_blank"><img src="../img/marina.png" alt="Marina" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1450,-700], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Heliport Marina</h3><a href="../img/heliport.png" target="_blank"><img src="../img/heliport.png" alt="Heliport Marina" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1250,-615], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Restaurant Chinois</h3><a href="../img/resto-chinois.png" target="_blank"><img src="../img/resto-chinois.png" alt="Restaurant Chinois" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1465,-450], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Flamme Olympique</h3><a href="../img/flamme-olympique.png" target="_blank"><img src="../img/flamme-olympique.png" alt="Flamme Olympique" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1110,-800], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Binco Little Seoul</h3><a href="../img/binco-little-seoul.png" target="_blank"><img src="../img/binco-little-seoul.png" alt="Binco Little Seoul" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Mirror Park
L.marker([-575,1125], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Mirror Park</h3><a href="../img/mirror-park.png" target="_blank"><img src="../img/mirror-park.png" alt="Mirror Park" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/mirror-park-zone.png" target="_blank"><img src="../img/mirror-park-zone.png" alt="Mirror Park" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-830,760], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Arcade</h3><a href="../img/arcade.jpg" target="_blank"><img src="../img/arcade.jpg" alt="Arcade" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-175,910], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>taxi</h3><a href="../img/taxi.png" target="_blank"><img src="../img/taxi.png" alt="taxi" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-25,1675], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Barrage</h3><a href="../img/barrage.png" target="_blank"><img src="../img/barrage.png" alt="Barrage" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([25,975], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Casino</h3><a href="../img/casino.png" target="_blank"><img src="../img/casino.png" alt="Casino" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-400,2500], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Noose</h3><a href="../img/noose.png" target="_blank"><img src="../img/noose.png" alt="Noose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-725,2800], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Plage Alcatraz</h3><a href="../img/plage-alcatraz.png" target="_blank"><img src="../img/plage-alcatraz.png" alt="Plage Alcatraz" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([375,2575], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>LTD Palomino</h3><a href="../img/ltd-palomino.png" target="_blank"><img src="../img/ltd-palomino.png" alt="LTD Palomino" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1100,760], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>LS Custom La Mesa</h3><a href="../img/ls-custom-mesa.png" target="_blank"><img src="../img/ls-custom-mesa.png" alt="LS Custom La Mesa" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-975,730], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Darnell / Usine Textile / Usine Textile</h3><a href="../img/darnell.png" target="_blank"><img src="../img/darnell.png" alt="Darnell / Usine Textile / Usine Textile" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-935,875], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Maibatsu Motors</h3><a href="../img/maibatsu.png" target="_blank"><img src="../img/maibatsu.png" alt="Maibatsu Motors" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([100,1150], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Hippodrome</h3><a href="../img/hippodrome.png" target="_blank"><img src="../img/hippodrome.png" alt="Hippodrome" style="width:300px;height:auto;border-radius:8px;"></div>');

//Bellevue / Del Perro / Vespucci
L.marker([-250,-1680], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Cimetière</h3><a href="../img/cimetiere.png" target="_blank"><img src="../img/cimetiere.png" alt="Cimetière" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/cimetiere-zone.png" target="_blank"><img src="../img/cimetiere-zone.png" alt="Cimetière" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-630,-1830], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Villas Plage / Maisons Vespucci</h3><a href="../img/villas-plage.png" target="_blank"><img src="../img/villas-plage.png" alt="Villas Plage / Maisons Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1050,-1590], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Fête Foraine</h3><a href="../img/fete-foraine.png" target="_blank"><img src="../img/fete-foraine.png" alt="Fête Foraine" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/fete-foraine-large.png" target="_blank"><img src="../img/fete-foraine-large.png" alt="Fête Foraine" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([300,-2240], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Kortz Center</h3><a href="../img/kortz-center.png" target="_blank"><img src="../img/kortz-center.png" alt="Kortz Center" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-110,-1300], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Tennis</h3><a href="../img/tennis.png" target="_blank"><img src="../img/tennis.png" alt="Tennis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-260,-1050], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Life Invader</h3><a href="../img/life-invader.png" target="_blank"><img src="../img/life-invader.png" alt="Life Invader" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-280,-975], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Akan Records / Rockford Records</h3><a href="../img/akan-records.png" target="_blank"><img src="../img/akan-records.png" alt="Akan Records / Rockford Records" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-525,-1090], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Studio Cinéma</h3><a href="../img/studio-cinema.png" target="_blank"><img src="../img/studio-cinema.png" alt="Studio Cinéma" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-680,-1190], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Parking Multicolore</h3><a href="../img/parking-multicolore.png" target="_blank"><img src="../img/parking-multicolore.png" alt="Parking Multicolore" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-760,-900], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Skatepark</h3><a href="../img/skatepark.png" target="_blank"><img src="../img/skatepark.png" alt="Skatepark" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-870,-860], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Mausolée Chinois / Sépulture</h3><a href="../img/mausolee-chinois.png" target="_blank"><img src="../img/mausolee-chinois.png" alt="Mausolée Chinois / Sépulture" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-850,-1070], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>PDP Vespucci</h3><a href="../img/pdp-vespucci-haut.png" target="_blank"><img src="../img/pdp-vespucci-haut.png" alt="PDP Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1090,-1010], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Canaux de Vespucci</h3><a href="../img/canaux-vespucci.png" target="_blank"><img src="../img/canaux-vespucci.png" alt="Canaux de Vespucci" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/canaux-vespucci-zone.png" target="_blank"><img src="../img/canaux-vespucci-zone.png" alt="Canaux de Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-905,-1155], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Burger Shot</h3><a href="../img/burger-shot.png" target="_blank"><img src="../img/burger-shot.png" alt="Burger Shot" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1055,-1275], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Hôtel V / Hôtel Five</h3><a href="../img/hotel-v.png" target="_blank"><img src="../img/hotel-v.png" alt="Hôtel V / Hôtel Five" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-875,-1250], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Arche</h3><a href="../img/arche.png" target="_blank"><img src="../img/arche.png" alt="Arche" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-670,-1450], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Motel</h3><a href="../img/motel.png" target="_blank"><img src="../img/motel.png" alt="Motel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-585,-1545], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Lombank</h3><a href="../img/lombank.png" target="_blank"><img src="../img/lombank.png" alt="Lombank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-350,-1450], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Quartier Morningwood</h3><a href="../img/morningwood.png" target="_blank"><img src="../img/morningwood.png" alt="Quartier Morningwood" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/morningwood-zone.png" target="_blank"><img src="../img/morningwood-zone.png" alt="Quartier Morningwood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-225,-770], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Concess Luxe / Luxury</h3><a href="../img/concess-luxe.png" target="_blank"><img src="../img/concess-luxe.png" alt="Concess Luxe / Luxury" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-250,-620], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Bijouterie</h3><a href="../img/bijouterie-devant.png" target="_blank"><img src="../img/bijouterie-devant.png" alt="Bijouterie" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/bijouterie-large.png" target="_blank"><img src="../img/bijouterie-large.png" alt="Bijouterie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-700,-1275], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Rue Piétonne</h3><a href="../img/rue-pietonne.png" target="_blank"><img src="../img/rue-pietonne.png" alt="Rue Piétonne" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/rue-pietonne-zone.png" target="_blank"><img src="../img/rue-pietonne-zone.png" alt="Rue Piétonne" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Univ
L.marker([50,-1150], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Golf</h3><a href="../img/golf-avant.png" target="_blank"><img src="../img/golf-avant.png" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/golf-arriere.png" target="_blank"><img src="../img/golf-arriere.png" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/golf-zone.png" target="_blank"><img src="../img/golf-zone.png" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([300,-1300], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Hotel Rose</h3><a href="../img/hotel-rose-avant.png" target="_blank"><img src="../img/hotel-rose-avant.png" alt="Hotel Rose" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/hotel-rose-arriere.png" target="_blank"><img src="../img/hotel-rose-arriere.png" alt="Hotel Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([200,-1600], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Université</h3><a href="../img/universite.png" target="_blank"><img src="../img/universite.png" alt="Université" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([100,-1500], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Villa Playboy</h3><a href="../img/playboy-avant.png" target="_blank"><img src="../img/playboy-avant.png" alt="Villa Playboy" style="width:300px;height:auto;border-radius:8px;"></a><a href="../img/playboy-arriere.png" target="_blank"><img src="../img/playboy-arriere.png" alt="Villa Playboy" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Nord
L.marker([1910,-65], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Ferme aux cochons</h3><a href="../img/ferme-cochon.png" target="_blank"><img src="../img/ferme-cochon.png" alt="Ferme aux cochons" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2100,-580], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Mine Abandonnée</h3><a href="../img/mine-abandonnee.png" target="_blank"><img src="../img/mine-abandonnee.png" alt="Mine Abandonnée" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2810,-295], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Chapelle</h3><a href="../img/chapelle.png" target="_blank"><img src="../img/chapelle.png" alt="Chapelle" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2050,-1860], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Vigneron</h3><a href="../img/vigneron.png" target="_blank"><img src="../img/vigneron.png" alt="Vigneron" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2100,-1550], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Totem</h3><a href="../img/totem.png" target="_blank"><img src="../img/totem.png" alt="Totem" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1900,-2550], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Villa Stark</h3><a href="../img/villa-stark.png" target="_blank"><img src="../img/villa-stark.png" alt="Villa Stark" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1080,-3115], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Chumash</h3><a href="../img/chumash.png" target="_blank"><img src="../img/chumash.png" alt="Chumash" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([475,-2920], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Fleeca GOH</h3><a href="../img/fleeca-goh.png" target="_blank"><img src="../img/fleeca-goh.png" alt="Fleeca GOH" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([80,-2975], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Pacific Bluffs</h3><a href="../img/pacific-bluffs.png" target="_blank"><img src="../img/pacific-bluffs.png" alt="Pacific Bluffs" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([800,-1775], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>LTD Tongva</h3><a href="../img/ltd-tongva.png" target="_blank"><img src="../img/ltd-tongva.png" alt="LTD Tongva" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1550,-1400], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Cuvette</h3><a href="../img/cuvette.png" target="_blank"><img src="../img/cuvette.png" alt="Cuvette" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2325,-2510], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Station Essence Zancudo</h3><a href="../img/station-essence-zancudo.png" target="_blank"><img src="../img/station-essence-zancudo.png" alt="Station Essence Zancudo" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3170,-2200], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Fort Zancudo / Base Militaire</h3><a href="../img/fort-zancudo.png" target="_blank"><img src="../img/fort-zancudo.png" alt="Fort Zancudo / Base Militaire" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4270,-2170], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Hookies</h3><a href="../img/hookies.png" target="_blank"><img src="../img/hookies.png" alt="Hookies" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4925,-1080], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Nudistes</h3><a href="../img/nudiste.png" target="_blank"><img src="../img/nudiste.png" alt="Nudistes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5335,-555], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Scierie</h3><a href="../img/scierie.png" target="_blank"><img src="../img/scierie.png" alt="Scierie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5580,-740], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Téléphérique</h3><a href="../img/telepherique.png" target="_blank"><img src="../img/telepherique.png" alt="Téléphérique" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6025,-440], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>PDP Paleto</h3><a href="../img/pdp-paleto.png" target="_blank"><img src="../img/pdp-paleto.png" alt="PDP Paleto" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6625,150], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>LS Custom Paleto</h3><a href="../img/ls-custom-paleto.png" target="_blank"><img src="../img/ls-custom-paleto.png" alt="LS Custom Paleto" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6255,-60], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Usine Poulet</h3><a href="../img/usine-poulet.png" target="_blank"><img src="../img/usine-poulet.png" alt="Usine Poulet" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([7200,80], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>La Pointe</h3><a href="../img/pointe.png" target="_blank"><img src="../img/pointe.png" alt="La Pointe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6425,1715], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Pops Diner</h3><a href="../img/pops-diner.png" target="_blank"><img src="../img/pops-diner.png" alt="Pops Diner" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5600,2225], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Maison Weed</h3><a href="../img/maison-weed.png" target="_blank"><img src="../img/maison-weed.png" alt="Maison Weed" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5550,500], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Mont Chiliad</h3><a href="../img/mont-chiliad.png" target="_blank"><img src="../img/mont-chiliad.png" alt="Mont Chiliad" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4940,1700], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>LTD Grapeseed</h3><a href="../img/ltd-grapeseed.png" target="_blank"><img src="../img/ltd-grapeseed.png" alt="LTD Grapeseed" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4365,1350], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Pêcherie</h3><a href="../img/pecherie.png" target="_blank"><img src="../img/pecherie.png" alt="Pêcherie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4775,2050], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Aérodrome Grapeseed</h3><a href="../img/aerodrome-grapeseed.png" target="_blank"><img src="../img/aerodrome-grapeseed.png" alt="Aérodrome Grapeseed" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5020,2420], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Ferme O"Neil</h3><a href="../img/oneil.png" target="_blank"><img src="../img/oneil.png" alt="Ferme ONeil" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4350,2890], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Silo</h3><a href="../img/silo.png" target="_blank"><img src="../img/silo.png" alt="Silo" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5180,3425], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Phare</h3><a href="../img/phare.png" target="_blank"><img src="../img/phare.png" alt="Phare" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4465,3775], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Maison Pêcheur</h3><a href="../img/maison-pecheur.png" target="_blank"><img src="../img/maison-pecheur.png" alt="Maison Pêcheur" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4140,2510], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>VPN</h3><a href="../img/vpn.png" target="_blank"><img src="../img/vpn.png" alt="VPN" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3715,3530], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Humane Labs</h3><a href="../img/humane-labs.png" target="_blank"><img src="../img/humane-labs.png" alt="Humane Labs" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3485,2720], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>You Tool</h3><a href="../img/youtool.png" target="_blank"><img src="../img/youtool.png" alt="You Tool" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3780,2460], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Hippies</h3><a href="../img/hippies.png" target="_blank"><img src="../img/hippies.png" alt="Hippies" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3850,1865], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Moulin</h3><a href="../img/moulin.png" target="_blank"><img src="../img/moulin.png" alt="Moulin" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3570,1565], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Motel Sandy</h3><a href="../img/motel-sandy.png" target="_blank"><img src="../img/motel-sandy.png" alt="Motel Sandy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3685,1845], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>PDP Sandy</h3><a href="../img/pdp-sandy.png" target="_blank"><img src="../img/pdp-sandy.png" alt="PDP Sandy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3250,1750], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Aéroport Sandy</h3><a href="../img/aeroport-sandy.png" target="_blank"><img src="../img/aeroport-sandy.png" alt="Aéroport Sandy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3050,2000], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Yellow Jack</h3><a href="../img/yellow-jack.png" target="_blank"><img src="../img/yellow-jack.png" alt="Yellow Jack" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3080,2380], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Casse Avion</h3><a href="../img/casse-avion.png" target="_blank"><img src="../img/casse-avion.png" alt="Casse Avion" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3450,350], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Cactus</h3><a href="../img/cactus.png" target="_blank"><img src="../img/cactus.png" alt="Cactus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3680,75], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Stab City</h3><a href="../img/stab-city.png" target="_blank"><img src="../img/stab-city.png" alt="Stab City" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2860,315], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Ciment</h3><a href="../img/ciment.png" target="_blank"><img src="../img/ciment.png" alt="Ciment" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2710,1190], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Fleeca Route 68</h3><a href="../img/fleeca-route-68.png" target="_blank"><img src="../img/fleeca-route-68.png" alt="Fleeca Route 68" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2575,1700], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>BolingBroke</h3><a href="../img/bolingbroke.png" target="_blank"><img src="../img/bolingbroke.png" alt="BolingBroke" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2825,2825], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Mine</h3><a href="../img/mine.png" target="_blank"><img src="../img/mine.png" alt="Mine" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2610,2550], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Dino Rose</h3><a href="../img/dino-rose.png" target="_blank"><img src="../img/dino-rose.png" alt="Dino Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2035,2270], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Éoliennes</h3><a href="../img/eolienne.png" target="_blank"><img src="../img/eolienne.png" alt="Éoliennes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1525,2725], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Raffinerie / Power Station / Palmer Station</h3><a href="../img/raffinerie.png" target="_blank"><img src="../img/raffinerie.png" alt="Raffinerie / Power Station / Palmer Station" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2200,1550], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Rodéo</h3><a href="../img/rodeo.png" target="_blank"><img src="../img/rodeo.png" alt="Rodéo" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1830,1485], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Croisement Ferme</h3><a href="../img/croisement-ferme.png" target="_blank"><img src="../img/croisement-ferme.png" alt="Croisement Ferme" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1875,1240], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>SCW</h3><a href="../img/scw.png" target="_blank"><img src="../img/scw.png" alt="SCW" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2350,1040], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Terrain de Cross</h3><a href="../img/terrain-cross.png" target="_blank"><img src="../img/terrain-cross.png" alt="Terrain de Cross" style="width:300px;height:auto;border-radius:8px;"></a></div>');