const center_x = 117.3;
const center_y = 172.8;
const scale_x = 0.02072;
const scale_y = 0.0205;

CUSTOM_CRS = L.extend({}, L.CRS.Simple, {
    projection: L.Projection.LonLat,
    scale: function(zoom) {

        return Math.pow(2, zoom);
    },
    zoom: function(sc) {

        return Math.log(sc) / 0.6931471805599453;
    },
	distance: function(pos1, pos2) {
        var x_difference = pos2.lng - pos1.lng;
        var y_difference = pos2.lat - pos1.lat;
        return Math.sqrt(x_difference * x_difference + y_difference * y_difference);
    },
	transformation: new L.Transformation(scale_x, center_x, -scale_y, center_y),
    infinite: true
});

var SateliteStyle = L.tileLayer('mapStyles/styleSatelite/{z}/{x}/{y}.jpg', {minZoom: 0,maxZoom: 8,noWrap: true,continuousWorld: false,attribution: 'Online map GTA V',id: 'SateliteStyle map',}),
	AtlasStyle	= L.tileLayer('mapStyles/styleAtlas/{z}/{x}/{y}.jpg', {minZoom: 0,maxZoom: 5,noWrap: true,continuousWorld: false,attribution: 'Online map GTA V',id: 'styleAtlas map',});
	// GridStyle	= L.tileLayer('mapStyles/styleGrid/{z}/{x}/{y}.png', {minZoom: 0,maxZoom: 5,noWrap: true,continuousWorld: false,attribution: 'Online map GTA V',id: 'styleGrid map',});

var PosGroup = L.layerGroup();
var Vinewood = L.layerGroup();
var SudLS = L.layerGroup();
var SudOuestLS = L.layerGroup();
var CentreVille = L.layerGroup();
var QuartierLS = L.layerGroup();
var MarinaPlage = L.layerGroup();
var MirrorPark = L.layerGroup();
var DelPerroVespucci = L.layerGroup();
var Univ = L.layerGroup();
var Nord = L.layerGroup();



var Icons = {
	"All 10-20" :PosGroup,
    "Vinewood" :Vinewood,
    "Sud LS" :SudLS,
    "Sud Ouest LS" :SudOuestLS,
    "Centre Ville" : CentreVille,
    "Quartier LS" :QuartierLS,
    "Marina / Plage" :MarinaPlage,
    "Mirror Park" :MirrorPark,
    "Bellevue / Del Perro / Vespucci" :DelPerroVespucci,
    "Université" : Univ,
    "Nord" : Nord,

};

var mymap = L.map('map', {
    crs: CUSTOM_CRS,
    minZoom: 1,
    maxZoom: 5,
    Zoom: 5,
    maxNativeZoom: 5,
    preferCanvas: true,
    layers: [SateliteStyle],
    center: [0, 0],
    zoom: 3,
});

var layersControl = L.control.layers({ "Satelite": SateliteStyle,"Atlas": AtlasStyle}, Icons).addTo(mymap);
// var layersControl = L.control.layers({ "Satelite": SateliteStyle,"Atlas": AtlasStyle,"Grid":GridStyle}, Icons).addTo(mymap);


function customIcon(icon){
	return L.icon({
		iconUrl: `blips/${icon}.png`,
		iconSize:     [20, 20],
		iconAnchor:   [20, 20], 
		popupAnchor:  [-10, -27]
	});
}

var X  = 0;
var Y = 0;

//L.marker([haut bas,gauche droite], {icon: customIcon(1)}).addTo(Icons["All 10-20"]).bindPopup("Description");
//'<div style="text-align:center;"><h3>Lieu</h3><a href="../img/nom-img.png" target="_blank"><img src="../img/nom-img.png" alt="Lieu" style="width:300px;height:auto;border-radius:8px;"></a></div>'

//Secteur Vinewood
L.marker([1575,-415], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Boule Orange</h3><a href="https://imgur.com/el3pvip.jpg" target="_blank"><img src="https://files.catbox.moe/jg94i5.jpg" alt="Boule Orange" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1125,-400], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Observatoire</h3><a href="https://imgur.com/5GgdBzQ.jpg" target="_blank"><img src="https://imgur.com/5GgdBzQ.jpg" alt="Observatoire" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([860,-800], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Parc à chiens</h3><a href="https://imgur.com/J4o5W6C.jpg" target="_blank"><img src="https://imgur.com/J4o5W6C.jpg" alt="Parc à chiens" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([880,-80], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Villas Lac / La Goutte</h3><a href="https://imgur.com/azLzWNF.jpg" target="_blank"><img src="https://imgur.com/azLzWNF.jpg" alt="Villas Lac" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1175,230], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Sisyphus</h3><a href="https://imgur.com/BYeYo8y.jpg" target="_blank"><img src="https://imgur.com/BYeYo8y.jpg" alt="Sisyphus" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/sWMiWc5.jpg" target="_blank"><img src="https://imgur.com/sWMiWc5.jpg" alt="Sisyphus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1200,675], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Lettres Vinewood</h3><a href="https://imgur.com/L4I99wo.jpg" target="_blank"><img src="https://imgur.com/L4I99wo.jpg" alt="Lettres Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1100,1400], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Fuente Blanca</h3><a href="https://imgur.com/toPVEGC.jpg" target="_blank"><img src="https://imgur.com/toPVEGC.jpg" alt="Fuente Blanca" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([800,1550], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Pipeline</h3><a href="https://i.imgur.com/YGGmroX.jpg" target="_blank"><img src="https://i.imgur.com/YGGmroX.jpg" alt="Pipeline" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([600,700], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Vinewood Bowl</h3><a href="https://imgur.com/SczgQDn.jpg" target="_blank"><img src="https://imgur.com/SczgQDn.jpg" alt="Vinewood Bowl" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/QfHE1nj.jpg" target="_blank"><img src="https://imgur.com/QfHE1nj.jpg" alt="Vinewood Bowl" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([320,-755], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Eclipse Tower</h3><a href="https://imgur.com/Qej2ULs.jpg" target="_blank"><img src="https://imgur.com/Qej2ULs.jpg" alt="Eclipse Tower" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([340,-35], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Manoir Blanc</h3><a href="https://imgur.com/0IJZQNH.jpg" target="_blank"><img src="https://imgur.com/0IJZQNH.jpg" alt="Manoir Blanc" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([200,75], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Alien</h3><a href="https://imgur.com/K2nhTge.jpg" target="_blank"><img src="https://imgur.com/K2nhTge.jpg" alt="Alien" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([330,360], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>LTD Vinewood</h3><a href="https://imgur.com/KwYZRbH.jpg" target="_blank"><img src="https://imgur.com/KwYZRbH.jpg" alt="LTD Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([260,650], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Station Essence VW</h3><a href="https://imgur.com/LPcWHbl.jpg" target="_blank"><img src="https://imgur.com/LPcWHbl.jpg" alt="Station Essence VW" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([170,355], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Cinema</h3><a href="https://imgur.com/18qWQWn.jpg" target="_blank"><img src="https://imgur.com/18qWQWn.jpg" alt="Cinema" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-20,600], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>PDP Vinewood</h3><a href="https://imgur.com/oEK8JXm.jpg" target="_blank"><img src="https://imgur.com/oEK8JXm.jpg" alt="PDP Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([80,320], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Parking Jaune</h3><a href="https://imgur.com/24amJNW.jpg" target="_blank"><img src="https://imgur.com/24amJNW.jpg" alt="Parking Jaune" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-355,405], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Mexico</h3><a href="https://imgur.com/fSkqgK9.jpg" target="_blank"><img src="https://imgur.com/fSkqgK9.jpg" alt="Mexico" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-300,330], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Fleeca Mexico</h3><a href="https://imgur.com/9P0jAws.jpg" target="_blank"><img src="https://imgur.com/9P0jAws.jpg" alt="Fleeca Mexico" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([290,160], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Marylin Monroe</h3><a href="https://imgur.com/P8Y7wDE.jpg" target="_blank"><img src="https://imgur.com/P8Y7wDE.jpg" alt="Marylin Monroe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-400,100], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Chantier Alta Street</h3><a href="https://imgur.com/rQiKYA2.jpg" target="_blank"><img src="https://imgur.com/rQiKYA2.jpg" alt="Chantier Alta Street" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-250,-175], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Rockford Plaza</h3><a href="https://imgur.com/MAzsNyr.jpg" target="_blank"><img src="https://imgur.com/MAzsNyr.jpg" alt="Rockford Plaza" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/IqGp2p6.jpg" target="_blank"><img src="https://imgur.com/IqGp2p6.jpg" alt="Rockford Plaza" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-200,-525], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Ancien Gouv</h3><a href="https://imgur.com/1l3Yv9C.jpg" target="_blank"><img src="https://imgur.com/1l3Yv9C.jpg" alt="Ancien Gouv" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-140,-350], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>LS Custom</h3><a href="https://imgur.com/HSd4zA1.jpg" target="_blank"><img src="https://imgur.com/HSd4zA1.jpg" alt="LS Custom" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([60,-670], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Epsilon</h3><a href="https://imgur.com/EvJiDSp.jpg" target="_blank"><img src="https://imgur.com/EvJiDSp.jpg" alt="Epsilon" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([280,-550], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Tequilala</h3><a href="https://imgur.com/0anWFnd.jpg" target="_blank"><img src="https://imgur.com/0anWFnd.jpg" alt="Tequilala" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([65,-55], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Benefactor</h3><a href="https://imgur.com/ZmqNLWL.jpg" target="_blank"><img src="https://imgur.com/ZmqNLWL.jpg" alt="Benefactor" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-20,-750], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Église Rockford</h3><a href="https://imgur.com/jh3qNEo.jpg" target="_blank"><img src="https://imgur.com/jh3qNEo.jpg" alt="Église Rockford" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([215,270], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Pacific Bank</h3><a href="https://imgur.com/QUlszmC.jpg" target="_blank"><img src="https://imgur.com/QUlszmC.jpg" alt="Pacific Bank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([90,80], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Go Postal</h3><a href="https://imgur.com/C70b9fS.jpg" target="_blank"><img src="https://imgur.com/C70b9fS.jpg" alt="Go Postal" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Sud Los Santos
L.marker([-2100,950], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Wardog</h3><a href="https://imgur.com/PWxNYwx.jpg" target="_blank"><img src="https://imgur.com/PWxNYwx.jpg" alt="Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2350,-385], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Vert</h3><a href="https://imgur.com/mFcnjUZ.jpg" target="_blank"><img src="https://imgur.com/mFcnjUZ.jpg" alt="Pont Vert" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2650,800], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Rouge</h3><a href="https://imgur.com/Ru0dfS4.jpg" target="_blank"><img src="https://imgur.com/Ru0dfS4.jpg" alt="Pont Rouge" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2340,370], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Rancho / Pont Vagos</h3><a href="https://imgur.com/GAq7v6D.jpg" target="_blank"><img src="https://imgur.com/GAq7v6D.jpg" alt="Pont Rancho / Pont Vagos" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2600,-150], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Chantier Naval</h3><a href="https://imgur.com/vsSvnvM.jpg" target="_blank"><img src="https://imgur.com/vsSvnvM.jpg" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/8NiqsYm.jpg" target="_blank"><img src="https://imgur.com/8NiqsYm.jpg" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/2vBFobe.jpg" target="_blank"><img src="https://imgur.com/2vBFobe.jpg" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3000,225], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Bugstars</h3><a href="https://imgur.com/EX2jOTo.jpg" target="_blank"><img src="https://imgur.com/EX2jOTo.jpg" alt="Bugstars" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/hfCeWfQ.jpg" target="_blank"><img src="https://imgur.com/hfCeWfQ.jpg" alt="Bugstars" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3100,550], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>MerryWeather</h3><a href="https://imgur.com/9BzGe7j.jpg" target="_blank"><img src="https://imgur.com/9BzGe7j.jpg" alt="MerryWeather" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/pYmvUXW.jpg" target="_blank"><img src="https://imgur.com/pYmvUXW.jpg" alt="MerryWeather" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2850,-450], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Post OP</h3><a href="https://imgur.com/6D7LGGZ.jpg" target="_blank"><img src="https://imgur.com/6D7LGGZ.jpg" alt="Post OP" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/TWuNkVW.jpg" target="_blank"><img src="https://imgur.com/TWuNkVW.jpg" alt="Post OP" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1950,1600], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pétrole</h3><a href="https://imgur.com/ZtlAupq.jpg" target="_blank"><img src="https://imgur.com/ZtlAupq.jpg" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/ptptxAe.jpg" target="_blank"><img src="https://imgur.com/ptptxAe.jpg" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/zr47bvS.jpg" target="_blank"><img src="https://imgur.com/zr47bvS.jpg" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2525,900], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Cypress</h3><a href="https://imgur.com/tN8P3WM.jpg" target="_blank"><img src="https://imgur.com/tN8P3WM.jpg" alt="Cypress" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2150,825], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Ammunation Wardog</h3><a href="https://imgur.com/inEvgl9.jpg" target="_blank"><img src="https://imgur.com/inEvgl9.jpg" alt="Ammunation Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2000,1070], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Fonderie</h3><a href="https://imgur.com/23m0iyc.jpg" target="_blank"><img src="https://imgur.com/23m0iyc.jpg" alt="Fonderie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2130,975], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Abattoir / Boucherie / Raven</h3><a href="https://imgur.com/54UtjDM.jpg" target="_blank"><img src="https://imgur.com/54UtjDM.jpg" alt="Abattoir / Boucherie / Raven" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/Tv7R5Zx.jpg" target="_blank"><img src="https://imgur.com/Tv7R5Zx.jpg" alt="Abattoir / Boucherie / Raven" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2475,1070], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Casse Bus</h3><a href="https://imgur.com/79XnKxT.jpg" target="_blank"><img src="https://imgur.com/79XnKxT.jpg" alt="Casse Bus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3310,1222], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Amazon</h3><a href="https://imgur.com/nJz5c8M.jpg" target="_blank"><img src="https://imgur.com/nJz5c8M.jpg" alt="Amazon" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Sud Ouest LS
L.marker([-2025,-1100], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>LS Custom Sud / LS Custom Aeroport</h3><a href="https://imgur.com/6RHvZ3F.jpg" target="_blank"><img src="https://imgur.com/6RHvZ3F.jpg" alt="LS Custom Sud / LS Custom Aeroport" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1750,-525], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Casse</h3><a href="https://imgur.com/hPWwq9v.jpg" target="_blank"><img src="https://imgur.com/hPWwq9v.jpg" alt="Casse" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2000,-250], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Maze Bank Arena</h3><a href="https://imgur.com/Y04v2CK.jpg" target="_blank"><img src="https://imgur.com/Y04v2CK.jpg" alt="Maze Bank Arena" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2700,-975], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Aéroport</h3><a href="https://imgur.com/2RVp9RZ.jpg" target="_blank"><img src="https://imgur.com/2RVp9RZ.jpg" alt="Aéroport" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/7mYj5fw.jpg" target="_blank"><img src="https://imgur.com/7mYj5fw.jpg" alt="Aéroport" style="width:300px;height:auto;border-radius:8px;"></a></div>');


//Secteur Centre Ville
L.marker([-600,345], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Pillbox Haut</h3><a href="https://imgur.com/5hwHS1w.jpg" target="_blank"><img src="https://imgur.com/5hwHS1w.jpg" alt="Pillbox Haut" style="width:300px;height:auto;border-radius:8px;"></a><h3>Pillbox Bas</h3><a href="https://imgur.com/hLuvmUW.jpg" target="_blank"><img src="https://imgur.com/hLuvmUW.jpg" alt="Pillbox Bas" style="width:300px;height:auto;border-radius:8px;"></a><h3>Tunnel Pillbox</h3><a href="https://imgur.com/JYO9vdk.jpg" target="_blank"><img src="https://imgur.com/JYO9vdk.jpg" alt="Tunnel Pillbox" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-750,155], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>FIB</h3><a href="https://imgur.com/7AO1ALJ.jpg" target="_blank"><img src="https://imgur.com/7AO1ALJ.jpg" alt="FIB" style="width:300px;height:auto;border-radius:8px;"></a><h3>Parking FIB</h3><a href="https://imgur.com/zLp9LYK.jpg" target="_blank"><img src="https://imgur.com/zLp9LYK.jpg" alt="Parking FIB" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/D5sjYgV.jpg" target="_blank"><img src="https://imgur.com/D5sjYgV.jpg" alt="Parking FIB" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-700,-10], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Gruppe6 / Union Depository</h3><a href="https://imgur.com/8ee858V.jpg" target="_blank"><img src="https://imgur.com/8ee858V.jpg" alt="Gruppe6 / Union Depository" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/ay6YcFl.jpg" target="_blank"><img src="https://imgur.com/ay6YcFl.jpg" alt="Gruppe6 / Union Depository" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-620,-140], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Arcadius</h3><a href="https://imgur.com/l67fWOi.jpg" target="_blank"><img src="https://imgur.com/l67fWOi.jpg" alt="Arcadius" style="width:300px;height:auto;border-radius:8px;"></a><h3>Parking Arcadius</h3><a href="https://imgur.com/80k3uQN.jpg" target="_blank"><img src="https://imgur.com/80k3uQN.jpg" alt="Parking Arcadius" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/fhqGViL.jpg" target="_blank"><img src="https://imgur.com/fhqGViL.jpg" alt="Parking Arcadius" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-640,-265], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Globe</h3><a href="https://imgur.com/wUwmu5O.jpg" target="_blank"><img src="https://imgur.com/wUwmu5O.jpg" alt="Globe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-780,-300], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Rouge</h3><a href="https://imgur.com/0k8OaIH.jpg" target="_blank"><img src="https://imgur.com/0k8OaIH.jpg" alt="Parking Rouge" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/7lM84QO.jpg" target="_blank"><img src="https://imgur.com/7lM84QO.jpg" alt="Parking Rouge" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-780,-440], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Blanc</h3><a href="https://imgur.com/msif6SA.jpg" target="_blank"><img src="https://imgur.com/msif6SA.jpg" alt="Parking Blanc" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-620,-520], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Musée</h3><a href="https://imgur.com/bo5PseK.jpg" target="_blank"><img src="https://imgur.com/bo5PseK.jpg" alt="Musée" style="width:300px;height:auto;border-radius:8px;"></a><h3>Tunnel Musée</h3><a href="https://imgur.com/WkuKU8r.jpg" target="_blank"><img src="https://imgur.com/WkuKU8r.jpg" alt="Tunnel Musée" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-765,-670], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Rose</h3><a href="https://imgur.com/GHHK48A.jpg" target="_blank"><img src="https://imgur.com/GHHK48A.jpg" alt="Parking Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-725,-760], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Cathédrale</h3><a href="https://imgur.com/sL0qOCB.jpg" target="_blank"><img src="https://imgur.com/sL0qOCB.jpg" alt="Cathédrale" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-950,-700], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>LTD Little Seoul</h3><a href="https://imgur.com/5lXhmrs.jpg" target="_blank"><img src="https://imgur.com/5lXhmrs.jpg" alt="LTD Little Seoul" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,-555], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Weazel News / Weazel</h3><a href="https://imgur.com/imIvXq8.jpg" target="_blank"><img src="https://imgur.com/imIvXq8.jpg" alt="Weazel News / Weazel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-980,-460], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chantier Weazel</h3><a href="https://imgur.com/6MyT6sL.jpg" target="_blank"><img src="https://imgur.com/6MyT6sL.jpg" alt="Chantier Weazel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,-310], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Pole Emploi</h3><a href="https://imgur.com/LLmxlLQ.jpg" target="_blank"><img src="https://imgur.com/LLmxlLQ.jpg" alt="Parking Pole Emploi" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-840,-60], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Tour Maze Bank</h3><a href="https://imgur.com/yc9gUrm.jpg" target="_blank"><img src="https://imgur.com/yc9gUrm.jpg" alt="Tour Maze Bank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1120,-30], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Ancien Concess</h3><a href="https://imgur.com/6c7goC4.jpg" target="_blank"><img src="https://imgur.com/6c7goC4.jpg" alt="Ancien Concess" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1040,-120], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chantier Concess</h3><a href="https://imgur.com/ILzP3dp.jpg" target="_blank"><img src="https://imgur.com/ILzP3dp.jpg" alt="Chantier Concess" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1090,150], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Caesar</h3><a href="https://imgur.com/0OhO9oI.jpg" target="_blank"><img src="https://imgur.com/0OhO9oI.jpg" alt="Caesar" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-880,60], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Ancien Parking MCD</h3><a href="https://imgur.com/dNZ6ix7.jpg" target="_blank"><img src="https://imgur.com/dNZ6ix7.jpg" alt="Ancien Parking MCD" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,215], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Places des cubes</h3><a href="https://imgur.com/dFadhZD.jpg" target="_blank"><img src="https://imgur.com/dFadhZD.jpg" alt="Places des cubes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1110,470], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Briques</h3><a href="https://imgur.com/vuSQsUw.jpg" target="_blank"><img src="https://imgur.com/vuSQsUw.jpg" alt="Parking Briques" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1010,470], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>PDP Mission Row</h3><a href="https://imgur.com/kYAlhf8.jpg" target="_blank"><img src="https://imgur.com/kYAlhf8.jpg" alt="PDP Mission Row" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-770,472], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chinatown</h3><a href="https://imgur.com/8O0pBdU.jpg" target="_blank"><img src="https://imgur.com/8O0pBdU.jpg" alt="Chinatown" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-640,450], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Entrepôt de Bus</h3><a href="https://imgur.com/DpIKp2I.jpg" target="_blank"><img src="https://imgur.com/DpIKp2I.jpg" alt="Entrepôt de Bus" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Quartier LS
L.marker([-1345,-200], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Bennys</h3><a href="https://imgur.com/4gw4XqC.jpg" target="_blank"><img src="https://imgur.com/4gw4XqC.jpg" alt="Bennys" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1560,-85], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Forum Drive / Chamberlain</h3><a href="https://imgur.com/Aes50eL.jpg" target="_blank"><img src="https://imgur.com/Aes50eL.jpg" alt="Forum Drive / Chamberlain" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/5aZ6Jzw.jpg" target="_blank"><img src="https://imgur.com/5aZ6Jzw.jpg" alt="Forum Drive / Chamberlain" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1960,120], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Groove Street / Raquette</h3><a href="https://imgur.com/kgXoorq.jpg" target="_blank"><img src="https://imgur.com/kgXoorq.jpg" alt="Groove Street / Raquette" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1770,60], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Mega Mall</h3><a href="https://imgur.com/uvFOAYZ.jpg" target="_blank"><img src="https://imgur.com/uvFOAYZ.jpg" alt="Mega Mall" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1575,190], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Météorite</h3><a href="https://imgur.com/O9DLdzM.jpg" target="_blank"><img src="https://imgur.com/O9DLdzM.jpg" alt="Météorite" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1620,260], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Librairie</h3><a href="https://imgur.com/iNbcG8I.jpg" target="_blank"><img src="https://imgur.com/iNbcG8I.jpg" alt="Librairie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1700,380], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Parking Davis</h3><a href="https://imgur.com/olnk3mk.jpg" target="_blank"><img src="https://imgur.com/olnk3mk.jpg" alt="Parking Davis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1845,480], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Rancho Nord</h3><a href="https://imgur.com/y6wg8RI.jpg" target="_blank"><img src="https://imgur.com/y6wg8RI.jpg" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/paxcR50.jpg" target="_blank"><img src="https://imgur.com/paxcR50.jpg" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/ThxCYk7.jpg" target="_blank"><img src="https://imgur.com/ThxCYk7.jpg" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2030,310], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Rancho Sud</h3><a href="https://imgur.com/sgnwU5S.jpg" target="_blank"><img src="https://imgur.com/sgnwU5S.jpg" alt="Rancho Sud" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1730,150], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Coiffeur Davis</h3><a href="https://imgur.com/8ojaiSw.jpg" target="_blank"><img src="https://imgur.com/8ojaiSw.jpg" alt="Coiffeur Davis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1325,160], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Unicorn</h3><a href="https://imgur.com/wCYeRVV.jpg" target="_blank"><img src="https://imgur.com/wCYeRVV.jpg" alt="Unicorn" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1395,260], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Morgue</h3><a href="https://imgur.com/5yfVICy.jpg" target="_blank"><img src="https://imgur.com/5yfVICy.jpg" alt="Morgue" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1450,350], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Medical Center</h3><a href="https://imgur.com/3pRmuq0.jpg" target="_blank"><img src="https://imgur.com/3pRmuq0.jpg" alt="Medical Center" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1350,810], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>La Mesa</h3><a href="https://imgur.com/mRr7qBi.jpg" target="_blank"><img src="https://imgur.com/mRr7qBi.jpg" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/oXkUjVW.jpg" target="_blank"><img src="https://imgur.com/oXkUjVW.jpg" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/JPsRsBm.jpg" target="_blank"><img src="https://imgur.com/JPsRsBm.jpg" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1550,1170], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Saint Fiacre</h3><a href="https://imgur.com/kdmuryV.jpg" target="_blank"><img src="https://imgur.com/kdmuryV.jpg" alt="Saint Fiacre" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1630,1345], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>El Burro</h3><a href="https://imgur.com/knRi9ap.jpg" target="_blank"><img src="https://imgur.com/knRi9ap.jpg" alt="El Burro" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1645,960], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Fridgit</h3><a href="https://imgur.com/nHfqA7i.jpg" target="_blank"><img src="https://imgur.com/nHfqA7i.jpg" alt="Fridgit" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/oFjTFAQ.jpg" target="_blank"><img src="https://imgur.com/oFjTFAQ.jpg" alt="Fridgit" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1780,750], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>SSX</h3><a href="https://imgur.com/QMsy85k.jpg" target="_blank"><img src="https://imgur.com/QMsy85k.jpg" alt="SSX" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1630,700], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Y</h3><a href="https://imgur.com/azCDlRv.jpg" target="_blank"><img src="https://imgur.com/azCDlRv.jpg" alt="Y" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1540,465], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Quartier Ukrainien</h3><a href="https://imgur.com/rNbOlzK.jpg" target="_blank"><img src="https://imgur.com/rNbOlzK.jpg" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/GNG0vd6.jpg" target="_blank"><img src="https://imgur.com/GNG0vd6.jpg" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/8vrlsAu.jpg" target="_blank"><img src="https://imgur.com/8vrlsAu.jpg" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Marina/Plage
L.marker([-1300,-1300], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Magasin Masque</h3><a href="https://imgur.com/y8aIuo3.jpg" target="_blank"><img src="https://imgur.com/y8aIuo3.jpg" alt="Magasin Masque" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1650,-1150], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Tennis Plage</h3><a href="https://imgur.com/9Na2obt.jpg" target="_blank"><img src="https://imgur.com/9Na2obt.jpg" alt="Tennis Plage" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1310,-1000], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Requin</h3><a href="https://imgur.com/xn8Ybst.jpg" target="_blank"><img src="https://imgur.com/xn8Ybst.jpg" alt="Requin" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1325,-775], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Marina</h3><a href="https://imgur.com/eb5voBG.jpg" target="_blank"><img src="https://imgur.com/eb5voBG.jpg" alt="Marina" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1450,-700], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Heliport Marina</h3><a href="https://imgur.com/x989u1h.jpg" target="_blank"><img src="https://imgur.com/x989u1h.jpg" alt="Heliport Marina" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1250,-615], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Restaurant Chinois</h3><a href="https://imgur.com/HskMdbh.jpg" target="_blank"><img src="https://imgur.com/HskMdbh.jpg" alt="Restaurant Chinois" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1465,-450], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Flamme Olympique</h3><a href="https://imgur.com/EymAx82.jpg" target="_blank"><img src="https://imgur.com/EymAx82.jpg" alt="Flamme Olympique" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1110,-800], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Binco Little Seoul</h3><a href="https://imgur.com/4rf4umY.jpg" target="_blank"><img src="https://imgur.com/4rf4umY.jpg" alt="Binco Little Seoul" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Mirror Park
L.marker([-575,1125], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Mirror Park</h3><a href="https://imgur.com/HqhrllT.jpg" target="_blank"><img src="https://imgur.com/HqhrllT.jpg" alt="Mirror Park" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/7Y4bPxU.jpg" target="_blank"><img src="https://imgur.com/7Y4bPxU.jpg" alt="Mirror Park" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-830,760], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Arcade</h3><a href="https://imgur.com/5udtOl8.jpg" target="_blank"><img src="https://imgur.com/5udtOl8.jpg" alt="Arcade" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-175,910], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Taxi</h3><a href="https://imgur.com/Ex6TVNl.jpg" target="_blank"><img src="https://imgur.com/Ex6TVNl.jpg" alt="taxi" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-25,1675], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Barrage</h3><a href="https://imgur.com/UxivweN.jpg" target="_blank"><img src="https://imgur.com/UxivweN.jpg" alt="Barrage" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([25,975], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Casino</h3><a href="https://imgur.com/ctIHFSD.jpg" target="_blank"><img src="https://imgur.com/ctIHFSD.jpg" alt="Casino" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-400,2500], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Noose</h3><a href="https://imgur.com/qu3rnBS.jpg" target="_blank"><img src="https://imgur.com/qu3rnBS.jpg" alt="Noose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-725,2800], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Plage Alcatraz / Crique Mara</h3><a href="https://imgur.com/IHxKZ8K.jpg" target="_blank"><img src="https://imgur.com/IHxKZ8K.jpg" alt="Plage Alcatraz" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([375,2575], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>LTD Palomino</h3><a href="https://imgur.com/PzCgJgN.jpg" target="_blank"><img src="https://imgur.com/PzCgJgN.jpg" alt="LTD Palomino" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1100,760], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>LS Custom La Mesa</h3><a href="https://imgur.com/Oc8LBRx.jpg" target="_blank"><img src="https://imgur.com/Oc8LBRx.jpg" alt="LS Custom La Mesa" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-975,730], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Darnell / Usine Couture / Usine Textile</h3><a href="https://imgur.com/RrzT3ba.jpg" target="_blank"><img src="https://imgur.com/RrzT3ba.jpg" alt="Darnell / Usine Textile / Usine Textile" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-935,875], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Maibatsu Motors</h3><a href="https://imgur.com/PfwPh71.jpg" target="_blank"><img src="https://imgur.com/PfwPh71.jpg" alt="Maibatsu Motors" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([100,1150], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Hippodrome</h3><a href="https://imgur.com/1SrsoWW.jpg" target="_blank"><img src="https://imgur.com/1SrsoWW.jpg" alt="Hippodrome" style="width:300px;height:auto;border-radius:8px;"></div>');

//Bellevue / Del Perro / Vespucci
L.marker([-250,-1680], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Cimetière</h3><a href="https://imgur.com/2QyY9ZS.jpg" target="_blank"><img src="https://imgur.com/2QyY9ZS.jpg" alt="Cimetière" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/61lrgf2.jpg" target="_blank"><img src="https://imgur.com/61lrgf2.jpg" alt="Cimetière" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-630,-1830], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Villas Plage / Maisons Vespucci</h3><a href="https://imgur.com/6tv51K3.jpg" target="_blank"><img src="https://imgur.com/6tv51K3.jpg" alt="Villas Plage / Maisons Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1050,-1590], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Fête Foraine</h3><a href="https://imgur.com/NXJHdvQ.jpg" target="_blank"><img src="https://imgur.com/NXJHdvQ.jpg" alt="Fête Foraine" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/YY0EHOl.jpg" target="_blank"><img src="https://imgur.com/YY0EHOl.jpg" alt="Fête Foraine" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([300,-2240], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Kortz Center</h3><a href="https://imgur.com/MQQWHG0.jpg" target="_blank"><img src="https://imgur.com/MQQWHG0.jpg" alt="Kortz Center" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-110,-1300], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Tennis</h3><a href="https://imgur.com/TYrg7pb.jpg" target="_blank"><img src="https://imgur.com/TYrg7pb.jpg" alt="Tennis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-260,-1050], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Life Invader</h3><a href="https://imgur.com/YXZHmrr.jpg" target="_blank"><img src="https://imgur.com/YXZHmrr.jpg" alt="Life Invader" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-280,-975], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Akan Records / Rockford Records</h3><a href="https://imgur.com/k8TJkpp.jpg" target="_blank"><img src="https://imgur.com/k8TJkpp.jpg" alt="Akan Records / Rockford Records" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-525,-1090], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Studio Cinéma</h3><a href="https://imgur.com/xz8zv6n.jpg" target="_blank"><img src="https://imgur.com/xz8zv6n.jpg" alt="Studio Cinéma" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-680,-1190], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Parking Multicolore</h3><a href="https://imgur.com/nEG9rt3.jpg" target="_blank"><img src="https://imgur.com/nEG9rt3.jpg" alt="Parking Multicolore" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-760,-900], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Skatepark</h3><a href="https://imgur.com/kHB7Izb.jpg" target="_blank"><img src="https://imgur.com/kHB7Izb.jpg" alt="Skatepark" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-870,-860], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Mausolée Chinois / Sépulture</h3><a href="https://imgur.com/w6HPvXb.jpg" target="_blank"><img src="https://imgur.com/w6HPvXb.jpg" alt="Mausolée Chinois / Sépulture" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-850,-1070], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>PDP Vespucci</h3><a href="https://imgur.com/I8yGgMK.jpg" target="_blank"><img src="https://imgur.com/I8yGgMK.jpg" alt="PDP Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1090,-1010], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Canaux de Vespucci</h3><a href="https://imgur.com/SjmQ3dh.jpg" target="_blank"><img src="https://imgur.com/SjmQ3dh.jpg" alt="Canaux de Vespucci" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/Jor0l9K.jpg" target="_blank"><img src="https://imgur.com/Jor0l9K.jpg" alt="Canaux de Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-905,-1155], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Burger Shot</h3><a href="https://imgur.com/ulNPNIs.jpg" target="_blank"><img src="https://imgur.com/ulNPNIs.jpg" alt="Burger Shot" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1055,-1275], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Hôtel V / Hôtel Five</h3><a href="https://imgur.com/VLcdaS4.jpg" target="_blank"><img src="https://imgur.com/VLcdaS4.jpg" alt="Hôtel V / Hôtel Five" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-875,-1250], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Arche</h3><a href="https://imgur.com/Lsagw7A.jpg" target="_blank"><img src="https://imgur.com/Lsagw7A.jpg" alt="Arche" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-670,-1450], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Motel</h3><a href="https://imgur.com/TcD89Yi.jpg" target="_blank"><img src="https://imgur.com/TcD89Yi.jpg" alt="Motel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-585,-1545], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Lombank</h3><a href="https://imgur.com/CshBYLA.jpg" target="_blank"><img src="https://imgur.com/CshBYLA.jpg" alt="Lombank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-350,-1450], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Quartier Morningwood</h3><a href="https://imgur.com/EiEXVnl.jpg" target="_blank"><img src="https://imgur.com/EiEXVnl.jpg" alt="Quartier Morningwood" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/02Lf6q2.jpg" target="_blank"><img src="https://imgur.com/02Lf6q2.jpg" alt="Quartier Morningwood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-225,-770], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Concess Luxe / Luxury</h3><a href="https://imgur.com/OUhTLwV.jpg" target="_blank"><img src="https://imgur.com/OUhTLwV.jpg" alt="Concess Luxe / Luxury" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-250,-620], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Bijouterie</h3><a href="https://imgur.com/ruMKFrF.jpg" target="_blank"><img src="https://imgur.com/ruMKFrF.jpg" alt="Bijouterie" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/Ebh8pZD.jpg" target="_blank"><img src="https://imgur.com/Ebh8pZD.jpg" alt="Bijouterie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-700,-1275], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Rue Piétonne</h3><a href="https://imgur.com/x9e3c39.jpg" target="_blank"><img src="https://imgur.com/x9e3c39.jpg" alt="Rue Piétonne" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/D97NvHE.jpg" target="_blank"><img src="https://imgur.com/D97NvHE.jpg" alt="Rue Piétonne" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Univ
L.marker([50,-1150], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Golf</h3><a href="https://imgur.com/RpsNszP.jpg" target="_blank"><img src="https://imgur.com/RpsNszP.jpg" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/yorEniI.jpg" target="_blank"><img src="https://imgur.com/yorEniI.jpg" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/QEgxoFP.jpg" target="_blank"><img src="https://imgur.com/QEgxoFP.jpg" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([300,-1300], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Hotel Rose</h3><a href="https://imgur.com/Gfc657z.jpg" target="_blank"><img src="https://imgur.com/Gfc657z.jpg" alt="Hotel Rose" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/FqSHWmP.jpg" target="_blank"><img src="https://imgur.com/FqSHWmP.jpg" alt="Hotel Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([200,-1600], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Université</h3><a href="https://imgur.com/tZtdYNo.jpg" target="_blank"><img src="https://imgur.com/tZtdYNo.jpg" alt="Université" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([100,-1500], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Villa Playboy</h3><a href="https://imgur.com/K6Swxoo.jpg" target="_blank"><img src="https://imgur.com/K6Swxoo.jpg" alt="Villa Playboy" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/dgZemLl.jpg" target="_blank"><img src="https://imgur.com/dgZemLl.jpg" alt="Villa Playboy" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Nord
L.marker([1910,-65], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Ferme aux cochons</h3><a href="https://imgur.com/EUyH3DI.jpg" target="_blank"><img src="https://imgur.com/EUyH3DI.jpg" alt="Ferme aux cochons" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2100,-580], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Mine Abandonnée</h3><a href="https://imgur.com/YETs6CQ.jpg" target="_blank"><img src="https://imgur.com/YETs6CQ.jpg" alt="Mine Abandonnée" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2810,-295], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Chapelle</h3><a href="https://imgur.com/hLydRO4.jpg" target="_blank"><img src="https://imgur.com/hLydRO4.jpg" alt="Chapelle" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2050,-1860], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Vigneron</h3><a href="https://imgur.com/iy1v7C6.jpg" target="_blank"><img src="https://imgur.com/iy1v7C6.jpg" alt="Vigneron" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2100,-1550], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Totem</h3><a href="https://imgur.com/4vL3VyX.jpg" target="_blank"><img src="https://imgur.com/4vL3VyX.jpg" alt="Totem" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1900,-2550], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Villa Stark</h3><a href="https://imgur.com/F52kplw.jpg" target="_blank"><img src="https://imgur.com/F52kplw.jpg" alt="Villa Stark" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1080,-3115], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Chumash</h3><a href="https://imgur.com/wO1vAI4.jpg" target="_blank"><img src="https://imgur.com/wO1vAI4.jpg" alt="Chumash" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([475,-2920], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Fleeca GOH</h3><a href="https://imgur.com/MVHaOFr.jpg" target="_blank"><img src="https://imgur.com/MVHaOFr.jpg" alt="Fleeca GOH" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([80,-2975], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Pacific Bluffs</h3><a href="https://imgur.com/9FpTo8o.jpg" target="_blank"><img src="https://imgur.com/9FpTo8o.jpg" alt="Pacific Bluffs" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([800,-1775], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>LTD Tongva</h3><a href="https://imgur.com/eqJjqOl.jpg" target="_blank"><img src="https://imgur.com/eqJjqOl.jpg" alt="LTD Tongva" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1550,-1400], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Cuvette</h3><a href="https://imgur.com/NYWTxEB.jpg" target="_blank"><img src="https://imgur.com/NYWTxEB.jpg" alt="Cuvette" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2325,-2510], {icon: customIcon("azur")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Station Essence Zancudo</h3><a href="https://imgur.com/f0zqlJ3.jpg" target="_blank"><img src="https://imgur.com/f0zqlJ3.jpg" alt="Station Essence Zancudo" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3170,-2200], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Fort Zancudo / Base Militaire</h3><a href="https://imgur.com/WgbTSKE.jpg" target="_blank"><img src="https://imgur.com/WgbTSKE.jpg" alt="Fort Zancudo / Base Militaire" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4270,-2170], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Hookies</h3><a href="https://imgur.com/XddHp5D.jpg" target="_blank"><img src="https://imgur.com/XddHp5D.jpg" alt="Hookies" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4925,-1080], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Nudistes</h3><a href="https://imgur.com/IHjF6HM.jpg" target="_blank"><img src="https://imgur.com/IHjF6HM.jpg" alt="Nudistes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5335,-555], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Scierie</h3><a href="https://imgur.com/F3P74Oo.jpg" target="_blank"><img src="https://imgur.com/F3P74Oo.jpg" alt="Scierie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5580,-740], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Téléphérique</h3><a href="https://imgur.com/V8bDJBK.jpg" target="_blank"><img src="https://imgur.com/V8bDJBK.jpg" alt="Téléphérique" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6025,-440], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>PDP Paleto</h3><a href="https://imgur.com/3DiG1FH.jpg" target="_blank"><img src="https://imgur.com/3DiG1FH.jpg" alt="PDP Paleto" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6625,150], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>LS Custom Paleto</h3><a href="https://imgur.com/rO2d2Yt.jpg" target="_blank"><img src="https://imgur.com/rO2d2Yt.jpg" alt="LS Custom Paleto" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6255,-60], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Usine Poulet</h3><a href="https://imgur.com/u7s3uYU.jpg" target="_blank"><img src="https://imgur.com/u7s3uYU.jpg" alt="Usine Poulet" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([7200,80], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>La Pointe</h3><a href="https://imgur.com/04fLNHQ.jpg" target="_blank"><img src="https://imgur.com/04fLNHQ.jpg" alt="La Pointe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([6425,1715], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Pops Diner</h3><a href="https://imgur.com/lgSKlJv.jpg" target="_blank"><img src="https://imgur.com/lgSKlJv.jpg" alt="Pops Diner" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5600,2225], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Maison Weed</h3><a href="https://imgur.com/Y4QWbpD.jpg" target="_blank"><img src="https://imgur.com/Y4QWbpD.jpg" alt="Maison Weed" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5550,500], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Mont Chiliad</h3><a href="https://imgur.com/Vd0sxhr.jpg" target="_blank"><img src="https://imgur.com/Vd0sxhr.jpg" alt="Mont Chiliad" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4940,1700], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>LTD Grapeseed</h3><a href="https://imgur.com/18ReXWf.jpg" target="_blank"><img src="https://imgur.com/18ReXWf.jpg" alt="LTD Grapeseed" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4365,1350], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Pêcherie</h3><a href="https://imgur.com/wHyCkjO.jpg" target="_blank"><img src="https://imgur.com/wHyCkjO.jpg" alt="Pêcherie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4775,2050], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Aérodrome Grapeseed</h3><a href="https://imgur.com/DmcR0nJ.jpg" target="_blank"><img src="https://imgur.com/DmcR0nJ.jpg" alt="Aérodrome Grapeseed" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5020,2420], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Ferme O"Neil</h3><a href="https://imgur.com/fhJPiIA.jpg" target="_blank"><img src="https://imgur.com/fhJPiIA.jpg" alt="Ferme ONeil" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4350,2890], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Silo</h3><a href="https://imgur.com/GTbwdIF.jpg" target="_blank"><img src="https://imgur.com/GTbwdIF.jpg" alt="Silo" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([5180,3425], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Phare</h3><a href="https://imgur.com/bqGlxJo.jpg" target="_blank"><img src="https://imgur.com/bqGlxJo.jpg" alt="Phare" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4465,3775], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Maison Pêcheur</h3><a href="https://imgur.com/WIcm7FX.jpg" target="_blank"><img src="https://imgur.com/WIcm7FX.jpg" alt="Maison Pêcheur" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([4140,2510], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>VPN</h3><a href="https://imgur.com/oRv5vNW.jpg" target="_blank"><img src="https://imgur.com/oRv5vNW.jpg" alt="VPN" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3715,3530], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Humane Labs</h3><a href="https://imgur.com/Io79tiu.jpg" target="_blank"><img src="https://imgur.com/Io79tiu.jpg" alt="Humane Labs" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3485,2720], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>You Tool</h3><a href="https://imgur.com/1L6uHUo.jpg" target="_blank"><img src="https://imgur.com/1L6uHUo.jpg" alt="You Tool" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3780,2460], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Hippies</h3><a href="https://imgur.com/piKXHZl.jpg" target="_blank"><img src="https://imgur.com/piKXHZl.jpg" alt="Hippies" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3850,1865], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Moulin</h3><a href="https://imgur.com/gtta9Vh.jpg" target="_blank"><img src="https://imgur.com/gtta9Vh.jpg" alt="Moulin" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3570,1565], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Motel Sandy</h3><a href="https://imgur.com/Ark1hsg.jpg" target="_blank"><img src="https://imgur.com/Ark1hsg.jpg" alt="Motel Sandy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3685,1845], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>PDP Sandy</h3><a href="https://imgur.com/6RZgsqF.jpg" target="_blank"><img src="https://imgur.com/6RZgsqF.jpg" alt="PDP Sandy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3250,1750], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Aéroport Sandy</h3><a href="https://imgur.com/1CXhDaU.jpg" target="_blank"><img src="https://imgur.com/1CXhDaU.jpg" alt="Aéroport Sandy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3050,2000], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Yellow Jack</h3><a href="https://imgur.com/zBxsz6x.jpg" target="_blank"><img src="https://imgur.com/zBxsz6x.jpg" alt="Yellow Jack" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3080,2380], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Casse Avion</h3><a href="https://imgur.com/DHriyUs.jpg" target="_blank"><img src="https://imgur.com/DHriyUs.jpg" alt="Casse Avion" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3450,350], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Cactus</h3><a href="https://imgur.com/DyKmprn.jpg" target="_blank"><img src="https://imgur.com/DyKmprn.jpg" alt="Cactus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([3680,75], {icon: customIcon("bleu-clair")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Stab City</h3><a href="https://imgur.com/2cCqhAb.jpg" target="_blank"><img src="https://imgur.com/2cCqhAb.jpg" alt="Stab City" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2860,315], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Ciment</h3><a href="https://imgur.com/DD9hLot.jpg" target="_blank"><img src="https://imgur.com/DD9hLot.jpg" alt="Ciment" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2710,1190], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Fleeca Route 68</h3><a href="https://imgur.com/5ruUePt.jpg" target="_blank"><img src="https://imgur.com/5ruUePt.jpg" alt="Fleeca Route 68" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2575,1700], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>BolingBroke</h3><a href="https://imgur.com/hXAHPii.jpg" target="_blank"><img src="https://imgur.com/hXAHPii.jpg" alt="BolingBroke" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2825,2825], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Mine</h3><a href="https://imgur.com/nBLZuhr.jpg" target="_blank"><img src="https://imgur.com/nBLZuhr.jpg" alt="Mine" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2610,2550], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Dino Rose</h3><a href="https://imgur.com/4DGPQSS.jpg" target="_blank"><img src="https://imgur.com/4DGPQSS.jpg" alt="Dino Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2035,2270], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Éoliennes</h3><a href="https://imgur.com/kFdE7Ey.jpg" target="_blank"><img src="https://imgur.com/kFdE7Ey.jpg" alt="Éoliennes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1525,2725], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Raffinerie / Power Station / Palmer Station</h3><a href="https://imgur.com/RbBCUGe.jpg" target="_blank"><img src="https://imgur.com/RbBCUGe.jpg" alt="Raffinerie / Power Station / Palmer Station" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2200,1550], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Rodéo</h3><a href="https://imgur.com/a5IXBvV.jpg" target="_blank"><img src="https://imgur.com/a5IXBvV.jpg" alt="Rodéo" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1830,1485], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Croisement Ferme</h3><a href="https://imgur.com/MYekanM.jpg" target="_blank"><img src="https://imgur.com/MYekanM.jpg" alt="Croisement Ferme" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1875,1240], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>SCW</h3><a href="https://imgur.com/5zYm5Jk.jpg" target="_blank"><img src="https://imgur.com/5zYm5Jk.jpg" alt="SCW" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([2350,1040], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Terrain de Cross</h3><a href="https://imgur.com/u7kZUjt.jpg" target="_blank"><img src="https://imgur.com/u7kZUjt.jpg" alt="Terrain de Cross" style="width:300px;height:auto;border-radius:8px;"></a></div>');